#!/usr/bin/env python3
"""Loading Programs exercise: dependency checks and Matrix data analysis."""

import os
import sys
import importlib
from typing import Dict, List, Tuple

os.environ['MPLBACKEND'] = 'Agg'


def check_dependencies(include_requests: bool = False) -> Tuple[bool, Dict[str, str]]:
    """Check required dependencies and print their versions.

    If include_requests is True, requests is treated as an additional optional tool
    for API data sources and is displayed in the dependency list.
    """
    dependencies: List[Tuple[str, str]] = [
        ('pandas', 'Data manipulation ready'),
        ('numpy', 'Numerical computation ready'),
        ('matplotlib', 'Visualization ready'),
    ]
    if include_requests:
        dependencies.append(('requests', 'Network access ready'))

    print("LOADING STATUS: Loading programs...")
    print("Checking dependencies:")

    all_ok = True
    versions = {}

    for package, description in dependencies:
        try:
            mod = importlib.import_module(package)
            version = getattr(mod, '__version__', 'unknown')
            versions[package] = version
            print(f"[OK] {package} ({version}) - {description}")
        except ImportError:
            print(f"[MISSING] {package} - Not installed")
            all_ok = False

    return all_ok, versions


def show_package_manager_comparison() -> None:
    """Display a small pip vs Poetry comparison for this project."""
    poetry_active = os.getenv('POETRY_ACTIVE') == '1'
    in_virtualenv = os.getenv('VIRTUAL_ENV') is not None

    print("\nDependency management comparison:")
    print("pip:    uses requirements.txt -> pip install -r requirements.txt")
    print("Poetry: uses pyproject.toml  -> poetry install")

    if poetry_active:
        print("Detected runtime: Poetry environment")
    elif in_virtualenv:
        print("Detected runtime: virtual environment (likely pip workflow)")
    else:
        print("Detected runtime: system/global Python")


def analyze_matrix_data():
    """Analyze Matrix data generated by numpy and create a visualization."""
    try:
        import pandas as pd
        import numpy as np
        import matplotlib.pyplot as plt

        print("Analyzing Matrix data...")

        data_points = 1000
        print(f"Processing {data_points} data points...")

        rng = np.random.default_rng(42)
        x_values = rng.normal(loc=0.0, scale=1.0, size=data_points)
        y_values = 0.6 * x_values + rng.normal(loc=0.0, scale=0.8, size=data_points)
        data = pd.DataFrame({'x': x_values, 'y': y_values})

        print("Generating visualization...")
        plt.figure(figsize=(9, 6))
        plt.scatter(data['x'], data['y'], alpha=0.35, s=16)
        plt.xlabel('Signal X')
        plt.ylabel('Signal Y')
        plt.title('Matrix Data Analysis')
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.savefig('matrix_analysis.png', dpi=140)
        plt.close()

        print("Analysis complete!")
        print("Results saved to: matrix_analysis.png")

    except ImportError as e:
        print(f"Error: Missing required package - {e}")
        print("Install dependencies with pip: pip install -r requirements.txt")
        print("Or with Poetry: poetry install")
        sys.exit(1)


def main():
    """Program entry point."""
    all_ok, _ = check_dependencies(include_requests=False)

    show_package_manager_comparison()

    if not all_ok:
        print("\nMissing dependencies detected.")
        print("Install with pip: pip install -r requirements.txt")
        print("Install with Poetry: poetry install")
        sys.exit(1)

    print()
    analyze_matrix_data()


if __name__ == '__main__':
    main()
